Don't update the image if not needed, create service dir

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,10 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
+source "$(dirname "$0")/config"
 
-docker pull jenkins
+if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q "$PLUGIN_IMAGE_VERSION" ; then
+  docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"
+fi
 
+mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE directory"
+chown dokku:dokku "$PLUGIN_DATA_ROOT"
